version: '3.9'

services:
  postgres:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - config/db-prod.env

  api-parking-control:
    depends_on:
      - postgres
    build: .
    ports:
      - "8081:8081"
    restart: always
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/parking-control-db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=123456

volumes:
  db_data: {}
